#!/usr/bin/env bash
# ==============================================================================
# Inox Cloudflare Tunnel Environment Toggle Script
# Toggles between 'localhost' and Cloudflare Tunnel URLs across:
#   - frontend/.env
#   - admin-portal/.env
#   - backend/.env
# ==============================================================================

TUNNEL_CONFIG="tunnel.env"

# 1. Ensure tunnel.env exists or create example
if [ ! -f "$TUNNEL_CONFIG" ]; then
    echo "Creating '$TUNNEL_CONFIG' configuration file..."
    cat << 'EOF' > "$TUNNEL_CONFIG"
# ==============================================================================
# Cloudflare Tunnel Configuration for Inox
# ==============================================================================
# Replace these URLs with the ones generated by `cloudflared tunnel --url ...`
# or your custom Cloudflare domain URLs.
# Note: Do NOT include trailing slashes (e.g. use https://backend.trycloudflare.com)
# ==============================================================================

CF_BACKEND_URL="https://your-backend-tunnel.trycloudflare.com"
CF_FRONTEND_URL="https://your-frontend-tunnel.trycloudflare.com"
CF_ADMIN_URL="https://your-admin-tunnel.trycloudflare.com"
CF_MINIO_URL="https://your-minio-tunnel.trycloudflare.com"
EOF
    echo "⚠️ Created '$TUNNEL_CONFIG' with placeholder URLs."
    echo "👉 Please edit '$TUNNEL_CONFIG' and enter your actual Cloudflare Tunnel URLs before enabling tunnel mode!"
    if [ "$1" != "--off" ] && [ "$1" != "-off" ] && [ "$1" != "local" ]; then
        exit 1
    fi
fi

# Load variables from tunnel.env
source "$TUNNEL_CONFIG"

# Strip trailing slashes just in case
CF_BACKEND_URL=$(echo "$CF_BACKEND_URL" | sed 's/*$//')
CF_FRONTEND_URL=$(echo "$CF_FRONTEND_URL" | sed 's/*$//')
CF_ADMIN_URL=$(echo "$CF_ADMIN_URL" | sed 's/*$//')
CF_MINIO_URL=$(echo "$CF_MINIO_URL" | sed 's/*$//')

# Derive WebSocket URL (replace https:// or http:// with wss:// or ws://)
if [[ "$CF_BACKEND_URL" == https://* ]]; then
    CF_BACKEND_WS_URL="wss://${CF_BACKEND_URL#https://}"
elif [[ "$CF_BACKEND_URL" == http://* ]]; then
    CF_BACKEND_WS_URL="ws://${CF_BACKEND_URL#http://}"
else
    CF_BACKEND_WS_URL="wss://$CF_BACKEND_URL"
    CF_BACKEND_URL="https://$CF_BACKEND_URL"
fi

show_help() {
    echo "Usage: ./toggle_tunnel.sh [MODE]"
    echo "Modes:"
    echo "  --on  | cloud   Switch environment variables to Cloudflare Tunnel URLs (from tunnel.env)"
    echo "  --off | local   Switch environment variables back to Localhost mode"
    echo "  --status        Show current configuration status"
    echo "  --help          Show this help message"
}

check_status() {
    if grep -q "http://localhost:8080" "frontend/.env" 2>/dev/null; then
        echo "CURRENT MODE: 🏠 Localhost (http://localhost:8080)"
    elif grep -q "trycloudflare.com\|cloudflare\|https://" "frontend/.env" 2>/dev/null; then
        CURRENT_URL=$(grep "^VITE_API_BASE_URL=" "frontend/.env" | cut -d'=' -f2 | sed 's|/api/v1.*||')
        echo "CURRENT MODE: ☁️  Cloudflare Tunnel ($CURRENT_URL)"
    else
        echo "CURRENT MODE: 🌐 Network IP / Custom Mode"
    fi
}

MODE="$1"

if [ -z "$MODE" ] || [ "$MODE" = "--status" ] || [ "$MODE" = "status" ]; then
    echo "========================================================================"
    echo "☁️  Inox Cloudflare Tunnel Status"
    echo "------------------------------------------------------------------------"
    check_status
    echo "------------------------------------------------------------------------"
    echo "Configured Tunnel URLs in '$TUNNEL_CONFIG':"
    echo "  Backend  : $CF_BACKEND_URL ($CF_BACKEND_WS_URL)"
    echo "  Frontend : $CF_FRONTEND_URL"
    echo "  Admin    : $CF_ADMIN_URL"
    echo "  MinIO    : $CF_MINIO_URL"
    echo "========================================================================"
    if [ -z "$MODE" ]; then
        echo "Run './toggle_tunnel.sh --on' to enable Tunnel mode or '--off' to return to Localhost."
    fi
    exit 0
fi

if [ "$MODE" = "--help" ] || [ "$MODE" = "-h" ]; then
    show_help
    exit 0
fi

if [ "$MODE" = "--on" ] || [ "$MODE" = "cloud" ] || [ "$MODE" = "on" ]; then
    if [[ "$CF_BACKEND_URL" == *"your-backend-tunnel"* ]] || [ -z "$CF_BACKEND_URL" ]; then
        echo "❌ Error: Please update '$TUNNEL_CONFIG' with your actual Cloudflare Tunnel URLs before running --on!"
        exit 1
    fi

    echo "========================================================================"
    echo "🔄 Enabling Cloudflare Tunnel Mode for Inox"
    echo "========================================================================"

    # 1. Update frontend/.env
    if [ -f "frontend/.env" ]; then
        sed -i "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${CF_BACKEND_URL}/api/v1|g" "frontend/.env"
        sed -i "s|^VITE_WS_BASE_URL=.*|VITE_WS_BASE_URL=${CF_BACKEND_WS_URL}/api/v1|g" "frontend/.env"
        sed -i "s|^VITE_MEDIA_STREAM_BASE_URL=.*|VITE_MEDIA_STREAM_BASE_URL=${CF_BACKEND_URL}/media/stream|g" "frontend/.env"
        if [ -n "$CF_MINIO_URL" ] && [[ "$CF_MINIO_URL" != *"your-minio-tunnel"* ]]; then
            sed -i "s|^VITE_MINIO_CONSOLE_URL=.*|VITE_MINIO_CONSOLE_URL=${CF_MINIO_URL}|g" "frontend/.env"
        fi
        echo "  ✔️ Updated frontend/.env"
    fi

    # 2. Update admin-portal/.env
    if [ -f "admin-portal/.env" ]; then
        sed -i "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${CF_BACKEND_URL}/api/v1|g" "admin-portal/.env"
        sed -i "s|^VITE_TELEMETRY_WS_URL=.*|VITE_TELEMETRY_WS_URL=${CF_BACKEND_WS_URL}/api/v1/admin/telemetry/ws|g" "admin-portal/.env"
        if [ -n "$CF_MINIO_URL" ] && [[ "$CF_MINIO_URL" != *"your-minio-tunnel"* ]]; then
            sed -i "s|^VITE_MINIO_BASE_URL=.*|VITE_MINIO_BASE_URL=${CF_MINIO_URL}|g" "admin-portal/.env"
        fi
        echo "  ✔️ Updated admin-portal/.env"
    fi

    # 3. Update backend/.env (Add tunnel origins to CORS and update MEDIA_STREAM_BASE_URL)
    if [ -f "backend/.env" ]; then
        sed -i "s|^MEDIA_STREAM_BASE_URL=.*|MEDIA_STREAM_BASE_URL=${CF_BACKEND_URL}/media/stream|g" "backend/.env"
        
        # Ensure CORS_ALLOWED_ORIGINS contains the frontend & admin tunnel URLs
        CURRENT_CORS=$(grep "^CORS_ALLOWED_ORIGINS=" "backend/.env" | cut -d'=' -f2-)
        NEW_CORS="$CURRENT_CORS"
        if [[ "$NEW_CORS" != *"$CF_FRONTEND_URL"* ]] && [ -n "$CF_FRONTEND_URL" ] && [[ "$CF_FRONTEND_URL" != *"your-frontend-tunnel"* ]]; then
            NEW_CORS="${NEW_CORS},${CF_FRONTEND_URL}"
        fi
        if [[ "$NEW_CORS" != *"$CF_ADMIN_URL"* ]] && [ -n "$CF_ADMIN_URL" ] && [[ "$CF_ADMIN_URL" != *"your-admin-tunnel"* ]]; then
            NEW_CORS="${NEW_CORS},${CF_ADMIN_URL}"
        fi
        # Also allow any *trycloudflare.com during quick tunnel testing
        if [[ "$NEW_CORS" != *".trycloudflare.com"* ]]; then
            NEW_CORS="${NEW_CORS},https://*.trycloudflare.com"
        fi
        sed -i "s|^CORS_ALLOWED_ORIGINS=.*|CORS_ALLOWED_ORIGINS=${NEW_CORS}|g" "backend/.env"
        echo "  ✔️ Updated backend/.env (CORS & Media Stream URL)"
    fi

    echo "------------------------------------------------------------------------"
    echo "✨ Cloudflare Tunnel Mode ENABLED!"
    echo "💡 Note: If your backend or frontend is currently running, restart them so they pick up the new environment variables."
    echo "========================================================================"

elif [ "$MODE" = "--off" ] || [ "$MODE" = "local" ] || [ "$MODE" = "off" ]; then
    echo "========================================================================"
    echo "🏠 Switching Inox back to Localhost Mode"
    echo "========================================================================"

    # 1. Update frontend/.env
    if [ -f "frontend/.env" ]; then
        sed -i "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=http://localhost:8080/api/v1|g" "frontend/.env"
        sed -i "s|^VITE_WS_BASE_URL=.*|VITE_WS_BASE_URL=ws://localhost:8080/api/v1|g" "frontend/.env"
        sed -i "s|^VITE_MEDIA_STREAM_BASE_URL=.*|VITE_MEDIA_STREAM_BASE_URL=http://localhost:8080/media/stream|g" "frontend/.env"
        sed -i "s|^VITE_MINIO_CONSOLE_URL=.*|VITE_MINIO_CONSOLE_URL=http://localhost:9001|g" "frontend/.env"
        echo "  ✔️ Reverted frontend/.env to Localhost"
    fi

    # 2. Update admin-portal/.env
    if [ -f "admin-portal/.env" ]; then
        sed -i "s|^VITE_API_BASE_URL=.*|VITE_API_BASE_URL=http://localhost:8080/api/v1|g" "admin-portal/.env"
        sed -i "s|^VITE_TELEMETRY_WS_URL=.*|VITE_TELEMETRY_WS_URL=ws://localhost:8080/api/v1/admin/telemetry/ws|g" "admin-portal/.env"
        sed -i "s|^VITE_MINIO_BASE_URL=.*|VITE_MINIO_BASE_URL=http://localhost:9000|g" "admin-portal/.env"
        echo "  ✔️ Reverted admin-portal/.env to Localhost"
    fi

    # 3. Update backend/.env
    if [ -f "backend/.env" ]; then
        sed -i "s|^MEDIA_STREAM_BASE_URL=.*|MEDIA_STREAM_BASE_URL=http://localhost:8080/media/stream|g" "backend/.env"
        sed -i "s|^CORS_ALLOWED_ORIGINS=.*|CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:3000|g" "backend/.env"
        echo "  ✔️ Reverted backend/.env to Localhost"
    fi

    echo "------------------------------------------------------------------------"
    echo "✨ Localhost Mode ENABLED!"
    echo "💡 Note: Restart any running dev servers (`npm run dev` or `go run ./cmd/server`) to apply."
    echo "========================================================================"
else
    echo "❌ Unknown mode: $MODE"
    show_help
    exit 1
fi
